# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ticket-buying-remix"
client_id = "49db1078e32326d7d2fbf3b070fda62c"
application_url = "https://monte-km-brunei-journalism.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,read_customers,read_metaobjects,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://monte-km-brunei-journalism.trycloudflare.com/auth/callback",
  "https://monte-km-brunei-journalism.trycloudflare.com/auth/shopify/callback",
  "https://monte-km-brunei-journalism.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "krb-kuro.myshopify.com"
