query getMovies($count: Int = 30) {
  metaobjects(first: $count, type: "movies", reverse: true) {
    nodes {
      handle
      id
      fields {
        key
        value
        reference {
          ... on MediaImage {
            image {
              altText
              url
            }
          }
        }
      }
    }
  }
}
