query getMovies {
  metaobjects(first: 10, type: "movies") {
    nodes {
      handle
      id
      fields {
        key
        value
        references(first: 10) {
          nodes {
            ... on Product {
              id
              title
              handle
              metaData: metafield(key: "meta_data", namespace: "custom") {
                key
                value
              }
              variants: variants(first: 5) {
                nodes {
                  id
                  title
                  price
                }
              }
            }
            ... on Metaobject {
              handle
              id
              fields {
                key
                value
              }
            }
          }
        }
        reference {
          ... on MediaImage {
            image {
              altText
              url
            }
          }
        }
      }
    }
  }
}
