query getProductsById($ids: [ID!]!) {
  nodes(ids: $ids) {
    ...on Product {
      id
      handle
      title
      variants(first: 10) {
        nodes {
          id
          title
          price {
            amount
          }
        }
      }
      metaData: metafield(namespace: "custom", key: "meta_data") {
        value
      }
    }
  }
}
